[package]
name = "boids"
version = "0.1.0"
authors = ["Simon Bourque <7109056+simon-bourque@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "boids"
path = "src/boids.rs"
